# Generated by Django 4.2.3 on 2023-08-01 06:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.TextField(default=django.utils.timezone.now, unique=True),
            preserve_default=False,
        ),
    ]
