# Generated by Django 4.2.3 on 2023-08-24 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_alter_transaction_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfermoney',
            name='recipient_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='transfermoney',
            name='sender_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
