# Generated by Django 4.2.4 on 2023-08-25 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_alter_transaction_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='receiver_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='sender_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
