# Generated by Django 4.2.3 on 2023-08-24 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_transfermoney_recipient_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfermoney',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_transactions', to='transactions.transaction'),
        ),
        migrations.AlterField(
            model_name='transfermoney',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_transactions', to='transactions.transaction'),
        ),
    ]
