# Generated by Django 4.2.3 on 2023-08-24 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_profile_photo'),
        ('transactions', '0006_alter_transfermoney_recipient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfermoney',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_transactions', to='accounts.userbankaccount'),
        ),
        migrations.AlterField(
            model_name='transfermoney',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_transactions', to='accounts.userbankaccount'),
        ),
    ]
